/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes2;

/**
 *
 * @author 42K4
 */
public class ChooseRobot extends javax.swing.JFrame {

    /**
     * Creates new form ChooseRobot
     */
    public ChooseRobot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OkButton = new javax.swing.JLabel();
        toMenuButton = new javax.swing.JLabel();
        MiniGELabel = new javax.swing.JLabel();
        MiniGELabel1 = new javax.swing.JLabel();
        MiniGELabel2 = new javax.swing.JLabel();
        MiniGELabel3 = new javax.swing.JLabel();
        MiniGELabel4 = new javax.swing.JLabel();
        MiniGELabel5 = new javax.swing.JLabel();
        MiniGH = new javax.swing.JLabel();
        MiniGH1 = new javax.swing.JLabel();
        MiniGH2 = new javax.swing.JLabel();
        MiniGH3 = new javax.swing.JLabel();
        MiniGH4 = new javax.swing.JLabel();
        MiniGH5 = new javax.swing.JLabel();
        MiniDef = new javax.swing.JLabel();
        MiniDef1 = new javax.swing.JLabel();
        MiniDef2 = new javax.swing.JLabel();
        MiniDef3 = new javax.swing.JLabel();
        MiniDef4 = new javax.swing.JLabel();
        MiniDef5 = new javax.swing.JLabel();
        MiniDgDown = new javax.swing.JLabel();
        MiniDgDown1 = new javax.swing.JLabel();
        MiniDgDown2 = new javax.swing.JLabel();
        MiniDgDown3 = new javax.swing.JLabel();
        MiniDgDown4 = new javax.swing.JLabel();
        MiniDgDown5 = new javax.swing.JLabel();
        MiniDgUp = new javax.swing.JLabel();
        MiniDgUp1 = new javax.swing.JLabel();
        MiniDgUp2 = new javax.swing.JLabel();
        MiniDgUp3 = new javax.swing.JLabel();
        MiniDgUp4 = new javax.swing.JLabel();
        MiniDgUp5 = new javax.swing.JLabel();
        MiniUdara = new javax.swing.JLabel();
        MiniUdara1 = new javax.swing.JLabel();
        MiniUdara2 = new javax.swing.JLabel();
        MiniUdara3 = new javax.swing.JLabel();
        MiniUdara4 = new javax.swing.JLabel();
        MiniUdara5 = new javax.swing.JLabel();
        MiniVertikal = new javax.swing.JLabel();
        MiniVertikal1 = new javax.swing.JLabel();
        MiniVertikal2 = new javax.swing.JLabel();
        MiniVertikal3 = new javax.swing.JLabel();
        MiniVertikal4 = new javax.swing.JLabel();
        MiniVertikal5 = new javax.swing.JLabel();
        MiniAirDef = new javax.swing.JLabel();
        MiniAirDef1 = new javax.swing.JLabel();
        MiniAirDef2 = new javax.swing.JLabel();
        MiniAirDef3 = new javax.swing.JLabel();
        MiniAirDef4 = new javax.swing.JLabel();
        MiniAirDef5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 255, 153));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        OkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkButtonMouseClicked(evt);
            }
        });
        getContentPane().add(OkButton);
        OkButton.setBounds(740, 200, 110, 60);
        getContentPane().add(toMenuButton);
        toMenuButton.setBounds(730, 270, 150, 40);

        MiniGELabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniEnergi.png"))); // NOI18N
        MiniGELabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniGELabelMouseClicked(evt);
            }
        });
        getContentPane().add(MiniGELabel);
        MiniGELabel.setBounds(70, 150, 90, 80);

        MiniGELabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniEnergi.png"))); // NOI18N
        MiniGELabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MiniGELabel1PropertyChange(evt);
            }
        });
        getContentPane().add(MiniGELabel1);
        MiniGELabel1.setBounds(100, 480, 80, 70);

        MiniGELabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniEnergi.png"))); // NOI18N
        getContentPane().add(MiniGELabel2);
        MiniGELabel2.setBounds(250, 470, 90, 100);

        MiniGELabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniEnergi.png"))); // NOI18N
        getContentPane().add(MiniGELabel3);
        MiniGELabel3.setBounds(410, 470, 90, 100);

        MiniGELabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniEnergi.png"))); // NOI18N
        getContentPane().add(MiniGELabel4);
        MiniGELabel4.setBounds(580, 460, 90, 100);

        MiniGELabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniEnergi.png"))); // NOI18N
        getContentPane().add(MiniGELabel5);
        MiniGELabel5.setBounds(730, 470, 90, 100);

        MiniGH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDarat.png"))); // NOI18N
        getContentPane().add(MiniGH);
        MiniGH.setBounds(210, 150, 80, 80);

        MiniGH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDarat.png"))); // NOI18N
        getContentPane().add(MiniGH1);
        MiniGH1.setBounds(90, 470, 80, 80);

        MiniGH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDarat.png"))); // NOI18N
        getContentPane().add(MiniGH2);
        MiniGH2.setBounds(250, 480, 80, 80);

        MiniGH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDarat.png"))); // NOI18N
        getContentPane().add(MiniGH3);
        MiniGH3.setBounds(410, 480, 80, 80);

        MiniGH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDarat.png"))); // NOI18N
        getContentPane().add(MiniGH4);
        MiniGH4.setBounds(570, 470, 80, 80);

        MiniGH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDarat.png"))); // NOI18N
        getContentPane().add(MiniGH5);
        MiniGH5.setBounds(730, 480, 80, 80);

        MiniDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDef.png"))); // NOI18N
        getContentPane().add(MiniDef);
        MiniDef.setBounds(340, 150, 90, 80);

        MiniDef1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDef.png"))); // NOI18N
        getContentPane().add(MiniDef1);
        MiniDef1.setBounds(90, 470, 90, 80);

        MiniDef2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDef.png"))); // NOI18N
        getContentPane().add(MiniDef2);
        MiniDef2.setBounds(250, 480, 90, 80);

        MiniDef3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDef.png"))); // NOI18N
        getContentPane().add(MiniDef3);
        MiniDef3.setBounds(410, 480, 90, 80);

        MiniDef4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDef.png"))); // NOI18N
        getContentPane().add(MiniDef4);
        MiniDef4.setBounds(570, 470, 90, 80);

        MiniDef5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDef.png"))); // NOI18N
        getContentPane().add(MiniDef5);
        MiniDef5.setBounds(730, 480, 90, 80);

        MiniDgDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgDown.png"))); // NOI18N
        getContentPane().add(MiniDgDown);
        MiniDgDown.setBounds(484, 154, 70, 80);

        MiniDgDown1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgDown.png"))); // NOI18N
        getContentPane().add(MiniDgDown1);
        MiniDgDown1.setBounds(100, 470, 70, 80);

        MiniDgDown2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgDown.png"))); // NOI18N
        getContentPane().add(MiniDgDown2);
        MiniDgDown2.setBounds(250, 480, 70, 80);

        MiniDgDown3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgDown.png"))); // NOI18N
        getContentPane().add(MiniDgDown3);
        MiniDgDown3.setBounds(410, 480, 70, 80);

        MiniDgDown4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgDown.png"))); // NOI18N
        getContentPane().add(MiniDgDown4);
        MiniDgDown4.setBounds(570, 480, 70, 80);

        MiniDgDown5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgDown.png"))); // NOI18N
        getContentPane().add(MiniDgDown5);
        MiniDgDown5.setBounds(730, 480, 70, 80);

        MiniDgUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgUp.png"))); // NOI18N
        getContentPane().add(MiniDgUp);
        MiniDgUp.setBounds(470, 290, 100, 80);

        MiniDgUp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgUp.png"))); // NOI18N
        getContentPane().add(MiniDgUp1);
        MiniDgUp1.setBounds(90, 480, 100, 80);

        MiniDgUp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgUp.png"))); // NOI18N
        getContentPane().add(MiniDgUp2);
        MiniDgUp2.setBounds(250, 480, 100, 80);

        MiniDgUp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgUp.png"))); // NOI18N
        getContentPane().add(MiniDgUp3);
        MiniDgUp3.setBounds(400, 480, 100, 80);

        MiniDgUp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgUp.png"))); // NOI18N
        getContentPane().add(MiniDgUp4);
        MiniDgUp4.setBounds(570, 470, 100, 80);

        MiniDgUp5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniDgUp.png"))); // NOI18N
        getContentPane().add(MiniDgUp5);
        MiniDgUp5.setBounds(720, 480, 100, 80);

        MiniUdara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniUdara.png"))); // NOI18N
        getContentPane().add(MiniUdara);
        MiniUdara.setBounds(60, 284, 100, 90);

        MiniUdara1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniUdara.png"))); // NOI18N
        getContentPane().add(MiniUdara1);
        MiniUdara1.setBounds(90, 470, 100, 90);

        MiniUdara2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniUdara.png"))); // NOI18N
        getContentPane().add(MiniUdara2);
        MiniUdara2.setBounds(250, 470, 100, 90);

        MiniUdara3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniUdara.png"))); // NOI18N
        getContentPane().add(MiniUdara3);
        MiniUdara3.setBounds(410, 480, 100, 90);

        MiniUdara4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniUdara.png"))); // NOI18N
        getContentPane().add(MiniUdara4);
        MiniUdara4.setBounds(570, 470, 100, 90);

        MiniUdara5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniUdara.png"))); // NOI18N
        getContentPane().add(MiniUdara5);
        MiniUdara5.setBounds(730, 470, 100, 90);

        MiniVertikal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniVertikal.png"))); // NOI18N
        getContentPane().add(MiniVertikal);
        MiniVertikal.setBounds(210, 290, 90, 80);

        MiniVertikal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniVertikal.png"))); // NOI18N
        getContentPane().add(MiniVertikal1);
        MiniVertikal1.setBounds(100, 470, 90, 80);

        MiniVertikal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniVertikal.png"))); // NOI18N
        getContentPane().add(MiniVertikal2);
        MiniVertikal2.setBounds(250, 470, 90, 80);

        MiniVertikal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniVertikal.png"))); // NOI18N
        getContentPane().add(MiniVertikal3);
        MiniVertikal3.setBounds(410, 470, 90, 80);

        MiniVertikal4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniVertikal.png"))); // NOI18N
        getContentPane().add(MiniVertikal4);
        MiniVertikal4.setBounds(580, 470, 90, 80);

        MiniVertikal5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniVertikal.png"))); // NOI18N
        getContentPane().add(MiniVertikal5);
        MiniVertikal5.setBounds(730, 470, 90, 80);

        MiniAirDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniAirDef.png"))); // NOI18N
        MiniAirDef.setText("jLabel6");
        getContentPane().add(MiniAirDef);
        MiniAirDef.setBounds(340, 290, 90, 80);

        MiniAirDef1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniAirDef.png"))); // NOI18N
        MiniAirDef1.setText("jLabel6");
        getContentPane().add(MiniAirDef1);
        MiniAirDef1.setBounds(90, 480, 90, 80);

        MiniAirDef2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniAirDef.png"))); // NOI18N
        MiniAirDef2.setText("jLabel6");
        getContentPane().add(MiniAirDef2);
        MiniAirDef2.setBounds(240, 480, 90, 80);

        MiniAirDef3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniAirDef.png"))); // NOI18N
        MiniAirDef3.setText("jLabel6");
        getContentPane().add(MiniAirDef3);
        MiniAirDef3.setBounds(410, 480, 90, 80);

        MiniAirDef4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniAirDef.png"))); // NOI18N
        MiniAirDef4.setText("jLabel6");
        getContentPane().add(MiniAirDef4);
        MiniAirDef4.setBounds(570, 480, 90, 80);

        MiniAirDef5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniAirDef.png"))); // NOI18N
        MiniAirDef5.setText("jLabel6");
        getContentPane().add(MiniAirDef5);
        MiniAirDef5.setBounds(730, 480, 90, 80);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 290, 100, 80);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/choose robot.png"))); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        getContentPane().add(background);
        background.setBounds(0, -10, 900, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkButtonMouseClicked
        // TODO add your handling code here:
        background.setVisible(false);
    }//GEN-LAST:event_OkButtonMouseClicked

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        // TODO add your handling code here:
        this.dispose();
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
    }//GEN-LAST:event_backgroundMouseClicked

    private void MiniGELabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniGELabelMouseClicked
        
    }//GEN-LAST:event_MiniGELabelMouseClicked

    private void MiniGELabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MiniGELabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MiniGELabel1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseRobot().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MiniAirDef;
    private javax.swing.JLabel MiniAirDef1;
    private javax.swing.JLabel MiniAirDef2;
    private javax.swing.JLabel MiniAirDef3;
    private javax.swing.JLabel MiniAirDef4;
    private javax.swing.JLabel MiniAirDef5;
    private javax.swing.JLabel MiniDef;
    private javax.swing.JLabel MiniDef1;
    private javax.swing.JLabel MiniDef2;
    private javax.swing.JLabel MiniDef3;
    private javax.swing.JLabel MiniDef4;
    private javax.swing.JLabel MiniDef5;
    private javax.swing.JLabel MiniDgDown;
    private javax.swing.JLabel MiniDgDown1;
    private javax.swing.JLabel MiniDgDown2;
    private javax.swing.JLabel MiniDgDown3;
    private javax.swing.JLabel MiniDgDown4;
    private javax.swing.JLabel MiniDgDown5;
    private javax.swing.JLabel MiniDgUp;
    private javax.swing.JLabel MiniDgUp1;
    private javax.swing.JLabel MiniDgUp2;
    private javax.swing.JLabel MiniDgUp3;
    private javax.swing.JLabel MiniDgUp4;
    private javax.swing.JLabel MiniDgUp5;
    private javax.swing.JLabel MiniGELabel;
    private javax.swing.JLabel MiniGELabel1;
    private javax.swing.JLabel MiniGELabel2;
    private javax.swing.JLabel MiniGELabel3;
    private javax.swing.JLabel MiniGELabel4;
    private javax.swing.JLabel MiniGELabel5;
    private javax.swing.JLabel MiniGH;
    private javax.swing.JLabel MiniGH1;
    private javax.swing.JLabel MiniGH2;
    private javax.swing.JLabel MiniGH3;
    private javax.swing.JLabel MiniGH4;
    private javax.swing.JLabel MiniGH5;
    private javax.swing.JLabel MiniUdara;
    private javax.swing.JLabel MiniUdara1;
    private javax.swing.JLabel MiniUdara2;
    private javax.swing.JLabel MiniUdara3;
    private javax.swing.JLabel MiniUdara4;
    private javax.swing.JLabel MiniUdara5;
    private javax.swing.JLabel MiniVertikal;
    private javax.swing.JLabel MiniVertikal1;
    private javax.swing.JLabel MiniVertikal2;
    private javax.swing.JLabel MiniVertikal3;
    private javax.swing.JLabel MiniVertikal4;
    private javax.swing.JLabel MiniVertikal5;
    private javax.swing.JLabel OkButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel toMenuButton;
    // End of variables declaration//GEN-END:variables
}
