/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes2;

/**
 *
 * @author 42K4
 */
public class ChooseLvl extends javax.swing.JFrame {

    /**
     * Creates new form ChooseLvl
     */
    private Player CurrentPlayer;
    private int selected;
    
    public ChooseLvl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        level1 = new javax.swing.JLabel();
        level2 = new javax.swing.JLabel();
        level3 = new javax.swing.JLabel();
        level4 = new javax.swing.JLabel();
        level5 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        pilihlevel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Level");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setName("Choose Level"); // NOI18N
        getContentPane().setLayout(null);

        level1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level1MouseClicked(evt);
            }
        });
        getContentPane().add(level1);
        level1.setBounds(50, 104, 140, 430);

        level2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level2MouseClicked(evt);
            }
        });
        getContentPane().add(level2);
        level2.setBounds(224, 110, 140, 420);

        level3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level3MouseClicked(evt);
            }
        });
        getContentPane().add(level3);
        level3.setBounds(394, 100, 140, 440);

        level4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level4MouseClicked(evt);
            }
        });
        getContentPane().add(level4);
        level4.setBounds(570, 110, 130, 430);

        level5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level5MouseClicked(evt);
            }
        });
        getContentPane().add(level5);
        level5.setBounds(734, 100, 140, 440);

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(760, 30, 100, 40);

        pilihlevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/choose level.png"))); // NOI18N
        getContentPane().add(pilihlevel);
        pilihlevel.setBounds(-6, 2, 910, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void level1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level1MouseClicked
    // TODO add your handling code here:
      if(this.CurrentPlayer.getLevel()>=1){
        ChooseRobot cr = new ChooseRobot();
        cr.setVisible(true);
        selected=1;
        
        this.dispose();
      }
    }//GEN-LAST:event_level1MouseClicked

    private void level2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level2MouseClicked
        this.dispose();
        ChooseRobot cr = new ChooseRobot();
        cr.setVisible(true);
    }//GEN-LAST:event_level2MouseClicked

    private void level3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level3MouseClicked
        this.dispose();
        ChooseRobot cr = new ChooseRobot();
        cr.setVisible(true);
    }//GEN-LAST:event_level3MouseClicked

    private void level4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level4MouseClicked
        this.dispose();
        ChooseRobot cr = new ChooseRobot();
        cr.setVisible(true);
    }//GEN-LAST:event_level4MouseClicked

    private void level5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level5MouseClicked
        this.dispose();
        ChooseRobot cr = new ChooseRobot();
        cr.setVisible(true);
    }//GEN-LAST:event_level5MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        MainMenu mn = new MainMenu();
        mn.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseLvl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseLvl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseLvl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseLvl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseLvl().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel level1;
    private javax.swing.JLabel level2;
    private javax.swing.JLabel level3;
    private javax.swing.JLabel level4;
    private javax.swing.JLabel level5;
    private javax.swing.JLabel pilihlevel;
    // End of variables declaration//GEN-END:variables
}
