/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes2;

/**
 *
 * @author 42K4
 */
public class Credits extends javax.swing.JFrame {

    /**
     * Creates new form Credits
     */
    public Credits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Credits = new java.awt.TextArea();
        backMenu = new javax.swing.JLabel();
        creditsMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        Credits.setPreferredSize(new java.awt.Dimension(350, 300));
        Credits.setText("                  Mini Robot Wars\n\n             Created by STIFunJava\n\n              Azka Ihsan Nurrahman\n                Indra Kusuma Putra\n               Nicolas Novian Ruslim\n                Farrell Yodihartomo\n               Muhammad Yusmanto\n\nCopyright (C) 2013 All Rights Reserved");
        getContentPane().add(Credits);
        Credits.setBounds(363, 201, 240, 200);

        backMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMenuMouseClicked(evt);
            }
        });
        getContentPane().add(backMenu);
        backMenu.setBounds(330, 450, 270, 30);

        creditsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/credits.png"))); // NOI18N
        getContentPane().add(creditsMenu);
        creditsMenu.setBounds(4, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMenuMouseClicked
        // TODO add your handling code here:
        this.dispose();
        MainMenu mu = new MainMenu();
        mu.setVisible(true);
    }//GEN-LAST:event_backMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credits().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea Credits;
    private javax.swing.JLabel backMenu;
    private javax.swing.JLabel creditsMenu;
    // End of variables declaration//GEN-END:variables
}
