/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes2;

import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author 42K4
 */
public class Level4 extends javax.swing.JFrame {
    ImageIcon newIcon = new ImageIcon();
    GameController GC = new GameController();
    MainController MC = new MainController(GC);
    ArrayList<Minirobot> mini = new ArrayList<Minirobot>();
    ArrayList<GiantRobot> giant = new ArrayList<GiantRobot>();
    ArrayList<Bullet> bullet = new ArrayList<Bullet>();
    /**
     * Creates new form Level4
     */
    public Level4() {
        initComponents();
        GC.Game();
        giant.add(new GiantRobot(25,25,new Rectangle(0,0,10,10),"lala",GC));
        mini.add(new MiniGE(0,100,10,0,new Rectangle(900,600,10,10),"lili",GC));
        giant.get(0).setEnemy(mini.get(0));
        GC.setGiant(giant);
        GC.setMini(mini);
        GC.setBullet(bullet);
        MC.run();
        LabelinVisible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 490, 80, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(810, 490, 80, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(720, 490, 80, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 490, 80, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 490, 80, 80);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 490, 80, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 490, 80, 80);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 490, 80, 80);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 490, 80, 80);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 490, 80, 80);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(810, 400, 80, 80);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(720, 400, 80, 80);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(630, 400, 80, 80);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(540, 400, 80, 80);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(450, 400, 80, 80);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(360, 400, 80, 80);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(270, 400, 80, 80);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(180, 400, 80, 80);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(90, 400, 80, 80);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 400, 80, 80);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(450, 310, 80, 80);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(90, 310, 80, 80);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(270, 310, 80, 80);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(0, 310, 80, 80);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel26);
        jLabel26.setBounds(540, 310, 80, 80);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel27);
        jLabel27.setBounds(180, 310, 80, 80);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(360, 310, 80, 80);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel29);
        jLabel29.setBounds(630, 310, 80, 80);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel30);
        jLabel30.setBounds(720, 310, 80, 80);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel31);
        jLabel31.setBounds(810, 310, 80, 80);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel32);
        jLabel32.setBounds(450, 220, 80, 80);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(90, 220, 80, 80);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel34);
        jLabel34.setBounds(270, 220, 80, 80);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel35);
        jLabel35.setBounds(0, 220, 80, 80);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel36);
        jLabel36.setBounds(540, 220, 80, 80);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel37);
        jLabel37.setBounds(180, 220, 80, 80);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel38);
        jLabel38.setBounds(360, 220, 80, 80);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel39);
        jLabel39.setBounds(630, 220, 80, 80);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel40);
        jLabel40.setBounds(720, 220, 80, 80);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel41);
        jLabel41.setBounds(810, 220, 80, 80);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel42);
        jLabel42.setBounds(450, 130, 80, 80);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel43);
        jLabel43.setBounds(90, 130, 80, 80);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel44);
        jLabel44.setBounds(270, 130, 80, 80);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel45);
        jLabel45.setBounds(0, 130, 80, 80);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel46);
        jLabel46.setBounds(540, 130, 80, 80);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel47);
        jLabel47.setBounds(180, 130, 80, 80);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel48);
        jLabel48.setBounds(360, 130, 80, 80);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel49);
        jLabel49.setBounds(630, 130, 80, 80);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel50);
        jLabel50.setBounds(720, 130, 80, 80);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transparant.png"))); // NOI18N
        getContentPane().add(jLabel51);
        jLabel51.setBounds(810, 130, 80, 80);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MiniEnergi.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 10, 120, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fixedArea/winter.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        LabelVisible();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
public void LabelinVisible(){
        this.jLabel1.setVisible(false);
        this.jLabel51.setVisible(false);
        this.jLabel3.setVisible(false);
        this.jLabel4.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jLabel6.setVisible(false);
        this.jLabel7.setVisible(false);
        this.jLabel8.setVisible(false);
        this.jLabel9.setVisible(false);
        this.jLabel10.setVisible(false);
        this.jLabel11.setVisible(false);
        this.jLabel12.setVisible(false);
        this.jLabel13.setVisible(false);
        this.jLabel14.setVisible(false);
        this.jLabel15.setVisible(false);
        this.jLabel16.setVisible(false);
        this.jLabel17.setVisible(false);
        this.jLabel18.setVisible(false);
        this.jLabel19.setVisible(false);
        this.jLabel20.setVisible(false);
        this.jLabel21.setVisible(false);
        this.jLabel22.setVisible(false);
        this.jLabel23.setVisible(false);
        this.jLabel24.setVisible(false);
        this.jLabel25.setVisible(false);
        this.jLabel26.setVisible(false);
        this.jLabel27.setVisible(false);
        this.jLabel28.setVisible(false);
        this.jLabel29.setVisible(false);
        this.jLabel30.setVisible(false);
        this.jLabel31.setVisible(false);
        this.jLabel32.setVisible(false);
        this.jLabel33.setVisible(false);
        this.jLabel34.setVisible(false);
        this.jLabel35.setVisible(false);
        this.jLabel36.setVisible(false);
        this.jLabel37.setVisible(false);
        this.jLabel38.setVisible(false);
        this.jLabel39.setVisible(false);
        this.jLabel40.setVisible(false);
        this.jLabel41.setVisible(false);
        this.jLabel42.setVisible(false);
        this.jLabel43.setVisible(false);
        this.jLabel44.setVisible(false);
        this.jLabel45.setVisible(false);
        this.jLabel46.setVisible(false);
        this.jLabel47.setVisible(false);
        this.jLabel48.setVisible(false);
        this.jLabel49.setVisible(false);
        this.jLabel50.setVisible(false);        
    }

    public void LabelVisible(){
        this.jLabel1.setVisible(true);
        this.jLabel51.setVisible(true);
        this.jLabel3.setVisible(true);
        this.jLabel4.setVisible(true);
        this.jLabel5.setVisible(true);
        this.jLabel6.setVisible(true);
        this.jLabel7.setVisible(true);
        this.jLabel8.setVisible(true);
        this.jLabel9.setVisible(true);
        this.jLabel10.setVisible(true);
        this.jLabel11.setVisible(true);
        this.jLabel12.setVisible(true);
        this.jLabel13.setVisible(true);
        this.jLabel14.setVisible(true);
        this.jLabel15.setVisible(true);
        this.jLabel16.setVisible(true);
        this.jLabel17.setVisible(true);
        this.jLabel18.setVisible(true);
        this.jLabel19.setVisible(true);
        this.jLabel20.setVisible(true);
        this.jLabel21.setVisible(true);
        this.jLabel22.setVisible(true);
        this.jLabel23.setVisible(true);
        this.jLabel24.setVisible(true);
        this.jLabel25.setVisible(true);
        this.jLabel26.setVisible(true);
        this.jLabel27.setVisible(true);
        this.jLabel28.setVisible(true);
        this.jLabel29.setVisible(true);
        this.jLabel30.setVisible(true);
        this.jLabel31.setVisible(true);
        this.jLabel32.setVisible(true);
        this.jLabel33.setVisible(true);
        this.jLabel34.setVisible(true);
        this.jLabel35.setVisible(true);
        this.jLabel36.setVisible(true);
        this.jLabel37.setVisible(true);
        this.jLabel38.setVisible(true);
        this.jLabel39.setVisible(true);
        this.jLabel40.setVisible(true);
        this.jLabel41.setVisible(true);
        this.jLabel42.setVisible(true);
        this.jLabel43.setVisible(true);
        this.jLabel44.setVisible(true);
        this.jLabel45.setVisible(true);
        this.jLabel46.setVisible(true);
        this.jLabel47.setVisible(true);
        this.jLabel48.setVisible(true);
        this.jLabel49.setVisible(true);
        this.jLabel50.setVisible(true);  
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
