/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes2;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author ikp
 */

public class MainMenu extends javax.swing.JFrame {

    Player CurrentPlayer;
    
    public MainMenu() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        textField1 = new java.awt.TextField();
        chooseplayer = new javax.swing.JLabel();
        newgame = new javax.swing.JLabel();
        continu = new javax.swing.JLabel();
        robopedia = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        credits = new javax.swing.JLabel();
        mainMenu = new javax.swing.JLabel();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        textField1.setText("Last Pemain");
        getContentPane().add(textField1);
        textField1.setBounds(760, 100, 50, 70);

        chooseplayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseplayerMouseClicked(evt);
            }
        });
        getContentPane().add(chooseplayer);
        chooseplayer.setBounds(780, 170, 50, 20);

        newgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newgameMouseClicked(evt);
            }
        });
        getContentPane().add(newgame);
        newgame.setBounds(720, 290, 120, 40);

        continu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuMouseClicked(evt);
            }
        });
        getContentPane().add(continu);
        continu.setBounds(720, 340, 120, 30);

        robopedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robopediaMouseClicked(evt);
            }
        });
        getContentPane().add(robopedia);
        robopedia.setBounds(720, 390, 120, 30);

        lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMouseClicked(evt);
            }
        });
        getContentPane().add(lab);
        lab.setBounds(720, 430, 110, 40);

        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusMouseClicked(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(740, 70, 80, 20);

        credits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsMouseClicked(evt);
            }
        });
        getContentPane().add(credits);
        credits.setBounds(730, 480, 100, 30);

        mainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main menu.png"))); // NOI18N
        getContentPane().add(mainMenu);
        mainMenu.setBounds(-20, -150, 980, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseplayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseplayerMouseClicked
        this.dispose();
        ChoosePlayer cp = new ChoosePlayer();
        cp.setVisible(true);
    }//GEN-LAST:event_chooseplayerMouseClicked

    private void newgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newgameMouseClicked
        this.dispose();
        Welcome wc = new Welcome();
        wc.setVisible(true);
    }//GEN-LAST:event_newgameMouseClicked

    private void continuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuMouseClicked
        this.dispose();
        LoadFrame lf = new LoadFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_continuMouseClicked

    private void statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseClicked
        this.dispose();
        ShowStatus ss = new ShowStatus();
        ss.setVisible(true);
    }//GEN-LAST:event_statusMouseClicked

    private void robopediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robopediaMouseClicked
        this.dispose();
        RobopediaMenu rp = new RobopediaMenu();
        rp.setVisible(true);
    }//GEN-LAST:event_robopediaMouseClicked

    private void labMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseClicked
        this.dispose();
        LabMenu lm = new LabMenu();
        lm.setVisible(true);
    }//GEN-LAST:event_labMouseClicked

    private void creditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsMouseClicked
        this.dispose();
        Credits cs = new Credits();
        cs.setVisible(true);
    }//GEN-LAST:event_creditsMouseClicked

    /*
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseplayer;
    private javax.swing.JLabel continu;
    private javax.swing.JLabel credits;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel mainMenu;
    private javax.swing.JLabel newgame;
    private javax.swing.JLabel robopedia;
    private javax.swing.JLabel status;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables

}
